apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeinfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeinfo
    app.kubernetes.io/part-of: nodeinfo
  name: nodeinfo
  namespace: cjerolim-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodeinfo
    weight: null
status: {}
