apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeinfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeinfo
    app.kubernetes.io/part-of: nodeinfo
  name: nodeinfo
  namespace: cjerolim-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodeinfo
status:
  loadBalancer: {}
